### ISSUE TITLE
您好，感谢您制作的脚本

### ISSUE THREAD

**Issue by zephyrxx** [winchesHe/chatGPT-prompt-scripts#1]
您好，非常感谢您制作的脚本，我测试了一段时间，想问一下能否做一些用起来更方便的修改
1. 输入prompt在对话框后，给一个选项让用户设置是不是要直接发送，目前是只复制在对话框里，有时候的prompt可能是“输出五个不同的解法”，无需修改直接发送出去就好了
2. 目前输入prompt在对话框后，整个prompt框会自动最小化，想问问能不能做成输入后不最小化，保持在右侧（或者给用户自由设置的选项）

非常感谢！

**Comment by winchesHe** [comment]
thx~, I got it

**Comment by winchesHe** [comment]
好了，我完成了，你可以更新到0.0.2版本去使用，如果可以的话可以帮我右上角点个star吗，这对我是很大的鼓励~

**Comment by zephyrxx** [comment]
用起来很方便，非常感谢！我点了star了
